config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end

  resources :users do
    resources :projects
  end

  get '/profile', to: 'users#show', as: :profile

  resources :projects do
    resources :comments
  end

  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :user_id, presence: true
  validates :project_id, presence: true
  validates :body, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :name, length: { minimum: 5 }
  validates :description, length: { minimum: 5 }
  validates :estimated_effort, presence: true
  validates :status, presence: true

  validates_inclusion_of :status, in: %w(created started stopped completed)

  scope :published, -> {
    where("published_at IS NOT NULL")
  }

  def self.include_user
    includes(:user).
      as_json(include: [:user])
  end

  def published=(val)
    value = ActiveRecord::Type::Boolean.new.cast(val)
    write_attribute(:published_at, value ? DateTime.now : nil)
  end

  def published
    self.published?
  end

  def published?
    self.published_at.present?
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :database_authenticatable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.encrypted_password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action"
    redirect_to(request.referrer || root_path)
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = project.comments.
    includes(:user).
    order(created_at: :desc).
    as_json(include: [:user])
    render json: {
      comments: @comments
    }
  end

  def create
    @comment = project.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      render json: {
        comment: @comment.as_json
      }
    end
  end

  def update
    @comment = project.comments.find(params[:id])
    if @comment.update(comment_params)
      render json: {
        comment: @comment.as_json
      }
    else
      render json: {
        errors: @comment.errors
      }
    end
  end

  def destroy
    @comment = project.comments.find(params[:id])
    authorize @comment
    if @comment.destroy
      render json: {
        status: :ok
      }
    else
      render json: {
        errors: @comment.errors
      }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def project
    @project ||= Project.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @projects = Project.published
    authorize @projects
    @projects = @projects.order(created_at: :desc).include_user
  end

  def show
    @project = Project.find(params[:id])
    authorize @project
    @project = @project.as_json(include: [:user, :comments])
  end

  def new
    @project = user_projects.build
    authorize @project
  end

  def create
    @project = user_projects.new(project_params)
    authorize @project
    if @project.save
      redirect_to @project, notice: "Awesome, you created a project!"
    else
      render 'new'
    end
  end

  def edit
    @project = user_projects.find(params[:id])
    @user = current_user
    authorize @project
  end

  def update
    @project = user_projects.find(params[:id])
    authorize @project
    if @project.update_attributes(project_params)
      render json: @project.as_json
    else
      render json: {
        errors: @project.errors
      }
    end
  end

  def destroy
    @project = user_projects.find(params[:id])
    authorize @project

    if @project.destroy
      render json: {
        status: :ok
      }
    else
      render json: {
        errors: @project.errors
      }
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description,
      :published, :status, :estimated_effort, :actual_effort)
  end

  def user_projects
    @projects ||= current_user.projects
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if !@user.persisted?
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      @user.save(validate:false)
    end

    sign_in_and_redirect @user, :event => :authentication
    set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, :only => [:create]

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = params[:id].blank? ? current_user : User.find(params[:id])
    authorize @user
  end

  def edit
    @user = params[:id].blank? ? current_user : User.find(params[:id])
    authorize @user
  end

  def update
    @user = params[:id].blank? ? current_user : User.find(params[:id])
    authorize @user
    if @user.update_attributes(user_params)
      render json: @user.as_json
    else
      render json: {
        errors: @user.errors
      }
    end
  end

  def destroy
    @user = User.find(params[:id])
    authorize @user
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:project).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def cp(path)
        "current" if current_page?(path)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash_message.html.erb
<% if flash.count > 0 %>
  <% flash.each do |key, value| %>
    <div class="row flash">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="alert alert-<%= key %>"><%= value %></div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_form_errors.html.erb
<% if form.errors.any? %>
    <div class="project-error-explanation">
        <h4><%= pluralize(form.errors.count, "error") %> prevented this project from being saved:</h4>
        
        <% form.errors.full_messages.each do |msg| %>
            <p class="project-error-item"><i class="fa fa-warning"></i> <%= msg %></p>
        <% end %>
        
    </div>
<% end %>

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">HOME IMPROVEMENT</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to 'HOME', projects_path, :class => "btn navbar-btn #{cp(projects_path)}", :id => "nav-link" %></li>
          <li><%= link_to "MY PROJECTS", profile_path, :class => "btn navbar-btn #{cp(profile_path)}", :id => "nav-link" %></li>
          <% if current_user.admin %>
            <li><%= link_to "USERS", users_path, :class => "btn navbar-btn #{cp(users_path)}", :id => "nav-link" %></li>
          <% end %>
          <li>
            <%= link_to "NEW PROJECT", new_project_path, :class => "btn navbar-btn", :id => "new-project-btn" %>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>
            <%= link_to "SIGN OUT", destroy_user_session_path, method: :get, :class => "btn navbar-btn", :id => "sign-in-btn"%>
          </li>
        <% else %>
          <li>
            <%= link_to "SIGN UP", new_registration_path(resource_name), :class => "btn navbar-btn", :id => "sign-in-btn" %>
          </li>
          <li>
            <%= link_to "SIGN IN", new_session_path(resource_name), :class => "btn navbar-btn", :id => "sign-in-btn" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeImp</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render 'layouts/top_nav' %>
  <%= render 'layouts/flash_message' %>
  <main class="container">

    <%= yield %>

  </main>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |form| %>

  <%= render partial: 'layouts/form_errors', locals: { form: @project } %>

  <div class="form-group form-name">
    <%= form.label :name, "Name:" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group form-description">
    <%= form.label :description, "Description:" %>
    <%= form.text_area :description, class: 'form-control', rows: '5' %>
  </div>
 
  <div class="form-group form-status">
    <label>Status: </label>
    <%= form.radio_button :status, 'created', checked: true %>
    <%= form.label :status, 'Created', :value => 'created' %>
    <%= form.radio_button :status, 'started' %>
    <%= form.label :status, 'Started', :value => 'started' %>
    <%= form.radio_button :status, 'stopped' %>
    <%= form.label :status, 'Stopped', :value => 'stopped' %>
    <%= form.radio_button :status, 'completed' , :id => 'statusCompletedSelected' %>
    <%= form.label :status, 'Completed', :value => 'completed' %>
  </div>

  <div class="form-group form-es-level">
    <label>Estimated level of effort: </label>
    <%= form.select :estimated_effort, options_for_select([[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10]]) %>
  </div>

  <div class="form-group form-ac-level" id="actualEffortForm" style="display: none" >
    <label>Actual level of effort: </label>
    <%= form.select :actual_effort, options_for_select([[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10]]) %>
  </div>

  <div class="form-group form-published">
    <label>Check box to make project public: </label>
    <%= form.check_box :published %>
  </div>

  <div class="text-center">
    <%= form.submit 'Save', :class => 'new-project-submit' %>
  </div>

<% end %>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">

    <%= react_component("ProjectsContainer", {
      projects: @projects,
      isAdmin: current_user.admin?
    }) %>

  </div>
  <div class="col-md-2"></div>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="row new-project-box">

      <%= render 'form' %>

    </div>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">

    <%= react_component("ProjectDetails", {
      project: @project,
      form_token: form_authenticity_token,
      current_user: current_user,
      is_admin: current_user.admin?
      })
    %>

  </div>
  <div class="col-md-2"></div>
</div>

app/views/users/index.html.erb
<% if @users.count > 0 %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Created on</th>
      <th>Projects</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user_path(user) %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.projects.count %></td>
      <td><%= link_to raw("<i class='fa fa-trash'></i>"), user_path(user),
      data: {:confirm => 'Are you sure?'}, method: :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<h4>There are no users yet.</h4>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    
    <%= react_component("ProjectsContainer", {
      projects: @user.projects.include_user,
      owner: @user,
      current_user: current_user
    }) %>

  </div>
  <div class="col-md-2"></div>
</div>